name: Latest  workflow
on: 
  push:
    branches:
      - main
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://dev.to/feed/https://dev.to/akshayvs, https://medium.com/feed/@digital.talker"
